spring:
  config:
    activate:
      on-profile: dev

  devtools:
    add-properties: true

  # Chú ý: datasource và jpa phải nằm dưới spring
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres  # Thường mặc định là postgres, không phải root
    password: "123456789"
    driver-class-name: org.postgresql.Driver

  jpa:
    # Phải đổi Dialect sang PostgreSQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true # Nên để true khi dev để dễ debug
    properties:
      hibernate:
        format_sql: true
  sendgrid:
    apiKey: ${SendGridApiKey}
    from-email: ${FromEmail}
    templateId: d-e889613106aa4f0094ca137eac6e1470
    verificationLink: http://localhost:8080/user/confirm-email
# Các cấu hình khác giữ nguyên nhưng phải đúng thụt lề
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

jwt:
  expiryMinutes: 5
  expiryDay: 14
  accessKey: ZC0Qq7m/gEvdJNftWRnj0aP7Y0EAlNL2nNpbsL4kGEA=
  refreshKey: uezYVL3Zu9Erf3apLHLhx65hca+FQ+rtLMn1EerJSpw=


openapi:
  service:
    api-docs: backend-service
    server: http://localhost:${server.port}
    title: Backend service
    version: 1.0.0


